package empleadosbdooneodatis;
// Generated 10-ene-2019 13:29:24 by Hibernate Tools 4.3.1



/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private int codEmpleado;
     private String nombre;
     private String apellidos;
     private String puesto;
     private int salario;

    public Empleados() {
    }

	
    public Empleados(int codEmpleado) {
        this.codEmpleado = codEmpleado;
    }
    public Empleados(int codEmpleado, String nombre, String apellidos, String puesto, int salario) {
       this.codEmpleado = codEmpleado;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.puesto = puesto;
       this.salario = salario;
    }
   
    public int getCodEmpleado() {
        return this.codEmpleado;
    }
    
    public void setCodEmpleado(int codEmpleado) {
        this.codEmpleado = codEmpleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public int getSalario() {
        return this.salario;
    }
    
    public void setSalario(int salario) {
        this.salario = salario;
    }




}


